# Generated by Django 5.2.17 on 2026-10-05 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], default='M', max_length=1)),
                ('faixa_etaria', models.CharField(choices=[('filhote', 'Filhote'), ('adulto', 'Adulto'), ('idoso', 'Idoso')], default='adulto', max_length=10, verbose_name='faixa etária')),
                ('idade_aproximada', models.CharField(help_text='Ex.: 3 meses, 2 anos, cerca de 8 anos.', max_length=40, verbose_name='idade aproximada')),
                ('localizacao', models.CharField(help_text='Região onde o animal está (sem endereço completo).', max_length=100, verbose_name='localização')),
                ('castrado', models.BooleanField(default=False)),
                ('vacinado', models.BooleanField(default=False)),
                ('vermifugado', models.BooleanField(default=False)),
                ('saude', models.TextField(blank=True, verbose_name='condições de saúde')),
                ('comportamento', models.TextField(blank=True)),
                ('descricao', models.TextField(blank=True, help_text='Texto público exibido na página de divulgação.', verbose_name='sobre o animal')),
                ('observacoes_internas', models.TextField(blank=True, help_text='Visível apenas para protetores autenticados.', verbose_name='observações internas')),
                ('foto', models.ImageField(upload_to='caes/', verbose_name='foto principal')),
                ('status', models.CharField(choices=[('tratamento', 'Em tratamento'), ('lar_temporario', 'Em lar temporário'), ('disponivel', 'Disponível para adoção'), ('em_adocao', 'Em processo de adoção'), ('adotado', 'Adotado')], default='tratamento', max_length=20)),
                ('data_adocao', models.DateField(blank=True, null=True, verbose_name='data da adoção')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cão',
                'verbose_name_plural': 'cães',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(default='Patas de Brasília', max_length=80)),
                ('slogan', models.CharField(default='Adoção responsável que transforma vidas.', max_length=160)),
                ('sobre', models.TextField(blank=True, default='Somos um grupo de protetores independentes que resgata, trata e encaminha cães para lares responsáveis.')),
                ('chave_pix', models.CharField(blank=True, max_length=120, verbose_name='chave PIX')),
                ('favorecido_pix', models.CharField(blank=True, max_length=120, verbose_name='favorecido do PIX')),
                ('instagram', models.CharField(blank=True, max_length=60, verbose_name='Instagram (@)')),
                ('whatsapp_geral', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp geral')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'configuração do site',
                'verbose_name_plural': 'configuração do site',
            },
        ),
        migrations.CreateModel(
            name='FotoCao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='caes/extras/')),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('cao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='animais.cao')),
            ],
            options={
                'verbose_name': 'foto adicional',
                'verbose_name_plural': 'fotos adicionais',
                'ordering': ['enviada_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, choices=[('tratamento', 'Em tratamento'), ('lar_temporario', 'Em lar temporário'), ('disponivel', 'Disponível para adoção'), ('em_adocao', 'Em processo de adoção'), ('adotado', 'Adotado')], max_length=20)),
                ('status_novo', models.CharField(choices=[('tratamento', 'Em tratamento'), ('lar_temporario', 'Em lar temporário'), ('disponivel', 'Disponível para adoção'), ('em_adocao', 'Em processo de adoção'), ('adotado', 'Adotado')], max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='animais.cao')),
            ],
            options={
                'verbose_name': 'histórico de status',
                'verbose_name_plural': 'históricos de status',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Protetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(help_text='Com DDD. Ex.: (61) 99999-0000. Usado no botão de contato para adoção.', max_length=20, verbose_name='WhatsApp')),
                ('regiao', models.CharField(blank=True, max_length=80, verbose_name='Região de atuação')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protetor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'protetor',
                'verbose_name_plural': 'protetores',
                'ordering': ['usuario__first_name', 'usuario__username'],
            },
        ),
        migrations.AddField(
            model_name='cao',
            name='protetor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caes', to='animais.protetor', verbose_name='protetor responsável'),
        ),
    ]
